<?php

/**
 * @file
 * Provides usage fields for the Commerce discount entity.
 */

/**
 * Implements hook_modules_enabled().
 *
 * Add commerce discount usage fields.
 *
 * @see commerce_discount_usage_install()
 */
function commerce_discount_usage_modules_enabled($modules) {
  foreach (commerce_discount_types() as $type => $value) {
    if (!field_info_instance('commerce_discount', 'commerce_discount_uses', $type)) {
      $instance = array(
        'field_name' => 'commerce_discount_uses',
        'entity_type' => 'commerce_discount',
        'bundle' => $type,
        'label' => t('Discount uses'),
      );
      field_create_instance($instance);
    }
    if (!field_info_instance('commerce_discount', 'commerce_discount_max_uses', $type)) {
      $instance = array(
        'field_name' => 'commerce_discount_max_uses',
        'entity_type' => 'commerce_discount',
        'bundle' => $type,
        'label' => t('Discount max uses'),
      );
      field_create_instance($instance);
    }
  }
}

/**
 * Implements hook_views_api().
 */
function commerce_discount_usage_views_api($module, $api) {
  if ($module == 'views') {
    return array(
      'version' => 2,
      'path' => drupal_get_path('module', 'commerce_discount_usage') . '/includes/views',
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function commerce_discount_usage_form_commerce_discount_form_alter(&$form, $form_state) {
  $form['commerce_discount_fields']['commerce_discount_max_uses']['#attributes']['class'][] = 'clearfix';
  $form['commerce_discount_fields']['commerce_discount_max_uses'][LANGUAGE_NONE][0]['value']['#title'] = t('Amount');

  $form['commerce_discount_fields']['commerce_discount_max_uses']['limit_uses'] = array(
    '#type' => 'select',
    '#options' => array(
      'unlimited' => t('Unlimited'),
      'limited' => t('Limited'),
    ),
    '#title' => t('Quantity'),
    '#weight' => -10,
  );

  $form['commerce_discount_fields']['commerce_discount_max_uses'][LANGUAGE_NONE][0]['value'] += array(
    '#states' => array(
        'disabled' => array(
          ':input[name="commerce_discount_fields[commerce_discount_max_uses][limit_uses]"]' => array('value' => 'unlimited'),
        ),
      ),
  );

  // Copy the discount-used field into the max uses wrapper and hide the
  // original.
  $form['commerce_discount_fields']['commerce_discount_max_uses']['discount_used'] = $form['commerce_discount_fields']['commerce_discount_uses'][LANGUAGE_NONE][0]['value'];
  $form['commerce_discount_fields']['commerce_discount_uses'][LANGUAGE_NONE][0]['value']['#access'] = FALSE;

  $form['commerce_discount_fields']['commerce_discount_max_uses']['discount_used']['#disabled'] = TRUE;
  $form['commerce_discount_fields']['commerce_discount_max_uses']['discount_used']['#title'] = t('Discount used');
  $form['commerce_discount_fields']['commerce_discount_max_uses']['discount_used']['#weight'] = 10;
}
